### ISSUE TITLE
nodejs 14

### ISSUE THREAD

**Issue by ansgarschulte** [herrevilkitten/telnet-rxjs#29]
Hi

I cannot connect a client to a Server with nodejs14. Any Ideas?

Client code:
```const Telnet = require('../../dist/telnet').Telnet;
const client = Telnet.client('www.yahoo.com:80');

let connected = false;

client.filter((event) => event instanceof Telnet.Event.Connected)
    .subscribe((event) => {
        connected = true;
        client.sendln('GET /');
    });

client.data
    .subscribe((data) => {
        if (!connected) {
            return;
        }
        console.log(data);
    });

client.connect();```

Output:

```/Users/atze/.nodenv/shims/node /Users/atze/Workspaces/telnet-rxjs/examples/javascript/client2.js
/Users/atze/Workspaces/telnet-rxjs/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

Error [ERR_SOCKET_CLOSED]: Socket is closed
    at new NodeError (internal/errors.js:322:7)
    at Socket._writeGeneric (net.js:788:8)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Connection.send (/Users/atze/Workspaces/telnet-rxjs/dist/connection.js:85:28)
    at Connection.sendln (/Users/atze/Workspaces/telnet-rxjs/dist/connection.js:93:14)
    at SafeSubscriber._next (/Users/atze/Workspaces/telnet-rxjs/examples/javascript/client2.js:9:16)
    at SafeSubscriber.__tryOrUnsub (/Users/atze/Workspaces/telnet-rxjs/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/atze/Workspaces/telnet-rxjs/node_modules/rxjs/internal/Subscriber.js:143:22) {
  code: 'ERR_SOCKET_CLOSED'
}

Process finished with exit code 1


```

**Comment by ansgarschulte** [comment]
Found the underlying Problem:
https://github.com/nodejs/node/commit/eeccd52b4ef2db3219fc76737bb00c1da669aea2#diff-218c57e035f64b18af4db037c96f13014aeb40a1f783d4f52919e2075621da0c

A fix could be like:

`this.PrivateSocket = new net.Socket({ readable: false, writable: false });`
