### ISSUE TITLE
telnet client example not worked

### ISSUE THREAD

**Issue by limenghua** [herrevilkitten/telnet-rxjs#4]
I use js code:
`const {Telnet} = require('telnet-rxjs');

const client = Telnet.client('www.yahoo.com:80');

let connected = false;

client.filter(
    (event)=> event instanceof Telnet.Event.Connected
)
.subscribe((event =>{
    connected = true;
    console.log('connected successd');
}));

client.data
    .subscribe((data) =>{
        if(! connected){
            return;
        }
        console.log(data);
    });

client.connect();`

when I run it use  node, exeption throwed:

 G:\git-server\js-netlib-practise\node_modules\telnet-rxjs\dist\connection.js:97
                throw new Error('No remoteUrl is defined');
                ^

Error: No remoteUrl is defined
    at Connection.connect (G:\git-server\js-netlib-practise\node_modules\telnet-rxjs\dist\connection.js:97:23)
    at Object.<anonymous> (G:\git-server\js-netlib-practise\telnet\telnet-rxjs-test.js:23:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

comment: I use node of version:v6.9.4

**Comment by herrevilkitten** [comment]
Oh hmm. Lemme look at that. Thanks for the report.

**Comment by herrevilkitten** [comment]
@limenghua should be resolved now

**Comment by herrevilkitten** [comment]
npm should be updated shortly.

**Comment by limenghua** [comment]
I updated from npm，it works well now.thanks!

**Comment by herrevilkitten** [comment]
Thanks for the report :)
